Repository embroider-build/release-plan, pull requests merged in 2025-02, with the labels that each got.

#119 allow you to define a semver tag when using prerelease
  src/plan.test.ts
  src/plan.ts
Labels: enhancement

#120 make name of release the same as the tag
  src/publish.test.ts
  src/publish.ts
Labels: enhancement

#122 rename embroider-release in error message to release-plan
  src/plan.ts
Labels: bug

#132 update pnpm
  package.json
Labels: internal

#133 update execa
  package.json
  pnpm-lock.yaml
  src/gather-changes.ts
  src/publish.ts
Labels: dependencies

#134 Update eslint - flat config and better prettier implementation
  .eslintignore
  .eslintrc.cjs
  .github/dependabot.yml
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  .gitignore
  .prettierignore
  eslint.config.mjs
  fixtures/pnpm/multi-lockfile/packages/c/package.json
  fixtures/pnpm/multi-lockfile/pnpm-workspace.yaml
  fixtures/pnpm/single-package/pnpm-workspace.yaml
  fixtures/pnpm/star-package/pnpm-workspace.yaml
  package.json
  pnpm-lock.yaml
  src/publish.ts
  tsconfig.json
Labels: internal
